# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Z7-Master.xdc

# Block Designs: bd/baremetal_sw_design/baremetal_sw_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design || ORIG_REF_NAME==baremetal_sw_design} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_processing_system7_0_0/baremetal_sw_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_processing_system7_0_0 || ORIG_REF_NAME==baremetal_sw_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_xlconcat_0_0/baremetal_sw_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_xlconcat_0_0 || ORIG_REF_NAME==baremetal_sw_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_axi_gpio_0_0/baremetal_sw_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_axi_gpio_0_0 || ORIG_REF_NAME==baremetal_sw_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_axi_gpio_0_1/baremetal_sw_design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_axi_gpio_0_1 || ORIG_REF_NAME==baremetal_sw_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_xbar_0/baremetal_sw_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_xbar_0 || ORIG_REF_NAME==baremetal_sw_design_xbar_0} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_ps7_0_axi_periph_0/baremetal_sw_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==baremetal_sw_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_rst_ps7_0_50M_0/baremetal_sw_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==baremetal_sw_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/baremetal_sw_design/ip/baremetal_sw_design_auto_pc_0/baremetal_sw_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_sw_design_auto_pc_0 || ORIG_REF_NAME==baremetal_sw_design_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/artur/baremetal_Software_project/baremetal_Software_project.gen/sources_1/bd/baremetal_sw_design/baremetal_sw_design_ooc.xdc
