# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/artur/baremetal_Software_project/baremetal_Software_project.srcs/sources_1/bd/baremetal_sw_design/ip/baremetal_sw_design_auto_pc_0/baremetal_sw_design_auto_pc_0.xci
# IP: The module: 'baremetal_sw_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/artur/baremetal_Software_project/baremetal_Software_project.gen/sources_1/bd/baremetal_sw_design/ip/baremetal_sw_design_auto_pc_0/baremetal_sw_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'baremetal_sw_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/artur/baremetal_Software_project/baremetal_Software_project.srcs/sources_1/bd/baremetal_sw_design/ip/baremetal_sw_design_auto_pc_0/baremetal_sw_design_auto_pc_0.xci
# IP: The module: 'baremetal_sw_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/artur/baremetal_Software_project/baremetal_Software_project.gen/sources_1/bd/baremetal_sw_design/ip/baremetal_sw_design_auto_pc_0/baremetal_sw_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'baremetal_sw_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
